In [1]:
import pandas as pd
import numpy as np

df = pd.DataFrame(np.random.randn(10, 5))
df

          0         1         2         3         4
0 -0.625602  1.603989  1.473258  1.033242 -0.525859
1 -0.090809  3.085557 -0.962889 -0.789208  0.774752
2 -0.153825 -2.506970  0.065059 -2.320492  1.042390
3  0.231783  0.192264 -0.737178 -2.726963  0.141254
4 -1.628335  0.228726  0.756788  0.199410 -0.301113
5  1.202061  0.354053  1.534630 -0.500715 -0.415946
6  0.256629 -1.772179 -0.154815 -0.056825 -0.146554
7 -0.593886  1.867480 -0.334545  0.438290 -2.286820
8 -1.892076  0.618616  1.561778  0.572730  0.585570
9  0.886657  0.581386  0.394556  1.693284 -0.457942

In [2]:
def ppr_data(df, df_name):
    df = df.groupby('ticketno').apply(custom_info).reset_index()  # ticketno 기준 병합 및 전처리 수행

    if df_name == 'train' and 'root_cause_type' in df.columns:
        print(f"Null 확인 : {df.isnull().values.any()}")
        df['root_cause_type'] = df['root_cause_type'].apply(lambda x: 0 if x == 'PowerFail' else (1 if x == 'LinkCut' else 2)) # 레이블 인코딩
        #df['root_cause_type'].value_counts().plot(kind = 'bar')

    df.to_csv(f"Q2_{df_name}_ppr.csv", index=False)

    return df

def custom_info(group):  # 임의로 작성된 전처리 코드입니다.
    d = {}
    group.sort_values(by='alarmtime', ascending=True, inplace=True)  # 경보 순서 정렬
    d['alarmmsg_original'] = ' '.join(group['alarmmsg_original'])  # 메시지 단순 병합
    if 'root_cause_type' in group.columns:  # 레이블 추출
        d['root_cause_type'] = group['root_cause_type'].iloc[0]  # 동일한 ticketno는 동일한 root_cause_type을 가짐
    else:
        d['root_cause_type'] = None  # 테스트 세트의 경우 정답 컬럼 없음
    return pd.Series(d, index=['alarmmsg_original', 'root_cause_type'])

train_df = pd.read_csv("Q2_train.csv")

df = ppr_data(train_df, "train")

Null 확인 : False

In [ ]:
df

In [ ]:
import tqdm
import pandas as pd
import numpy as np

messages = []
for i, message in enumerate(df['alarmmsg_original']):
    message = message.split(' ')
    # if i < 5:
    #     print('원래 message', message)
    message = list(set(message))
    # if i < 5 and len(message) > 0:
    #     print('수정된 message', message)
    messages.append(message)

for k in range(100):
    if len(messages[k]) > 1:
        print(' '.join(messages[k]))